import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from './firebase';

const DUMMY_PROPERTIES = [
  {
    title: "Modern 2BHK Flat in Dhanmondi",
    category: "Family",
    description: "Spacious south-facing flat with great ventilation. Built-in cabinets and modern kitchen fittings.",
    rent: 28000,
    deposit: 56000,
    utilityDetails: "Electricity (prepaid), Gas 1200tk/mo",
    city: "Dhaka",
    area: "Dhanmondi",
    address: "Road 15, Dhanmondi R/A",
    amenities: ["Lift", "Generator", "Security", "Balcony", "Gas (Line)"],
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1000", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Abdur Rahman",
    ownerPhone: "01711223344",
    ownerId: "system_dummy_1",
    isFeatured: true
  },
  {
    title: "Luxury Bachelor Studio for Student",
    category: "Bachelor",
    description: "Perfect for students or young professionals. Fully furnished with high-speed internet.",
    rent: 12000,
    deposit: 12000,
    utilityDetails: "All included in rent except electricity",
    city: "Dhaka",
    area: "Mirpur 10",
    address: "Block C, Road 2",
    amenities: ["Generator", "Internet", "A/C", "Security"],
    images: ["https://images.unsplash.com/photo-1536376074432-ef12fa477982?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Karim Mia",
    ownerPhone: "01811556677",
    ownerId: "system_dummy_2"
  },
  {
    title: "Spacious Office Space Near IT Hub",
    category: "Office",
    description: "1500 sq ft open plan office. Ideal for startups or back-office operations.",
    rent: 65000,
    deposit: 130000,
    utilityDetails: "Commercial rates apply",
    city: "Dhaka",
    area: "Banani",
    address: "Kemal Ataturk Avenue",
    amenities: ["Lift", "Generator", "Parking", "Security", "CCTV"],
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Hossain Traders Ltd.",
    ownerPhone: "01911998877",
    ownerId: "system_dummy_3"
  },
  {
    title: "Cozy Family Apartment in Uttara",
    category: "Family",
    description: "Quiet residential neighborhood, near schools and hospitals. 3 Bedrooms and 3 Baths.",
    rent: 35000,
    deposit: 70000,
    utilityDetails: "Gas 1080tk, Water 500tk fixed",
    city: "Dhaka",
    area: "Uttara Sector 7",
    address: "Near Rajuk College",
    amenities: ["Lift", "Generator", "Security", "Balcony", "Gas (Line)", "Parking"],
    images: ["https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Mrs. Sultana",
    ownerPhone: "01755443322",
    ownerId: "system_dummy_4"
  },
  {
    title: "Premium Penthouse in Gulshan 2",
    category: "Family",
    description: "Ultra-luxury penthouse with private roof deck and infinity pool view. 4 master suites.",
    rent: 250000,
    deposit: 500000,
    utilityDetails: "Central AC, high maintenance fee",
    city: "Dhaka",
    area: "Gulshan 2",
    address: "Road 71, Gulshan",
    amenities: ["Lift", "Pool", "Gym", "Parking", "Security", "CCTV"],
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Zaker Aziz",
    ownerPhone: "01700112233",
    ownerId: "system_dummy_5",
    isFeatured: true
  },
  {
    title: "Compact Room for Students - Bashundhara",
    category: "Bachelor",
    description: "Walking distance to IUB and NSU. Safe and quiet environment.",
    rent: 9000,
    deposit: 9000,
    utilityDetails: "Electricity as per meter",
    city: "Dhaka",
    area: "Bashundhara R/A",
    address: "Block D",
    amenities: ["Internet", "Security", "Cleaning"],
    images: ["https://images.unsplash.com/photo-1555854817-5b2260d50c5b?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Rafiqul Islam",
    ownerPhone: "01822334455",
    ownerId: "system_dummy_6"
  },
  {
    title: "Small Office Space in Motijheel",
    category: "Office",
    description: "Centrally located commercial space. Best for small agencies or consultancy firms.",
    rent: 25000,
    deposit: 75000,
    utilityDetails: "Commercial gas and water",
    city: "Dhaka",
    area: "Motijheel",
    address: "Dilkusha C/A",
    amenities: ["Lift", "Security", "Telephone Line"],
    images: ["https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Dilkusha Properties",
    ownerPhone: "01511223344",
    ownerId: "system_dummy_7"
  },
  {
    title: "Affordable 2-Bed Flat in Khilgaon",
    category: "Family",
    description: "Family friendly area with plenty of restaurants and shops nearby.",
    rent: 18000,
    deposit: 36000,
    utilityDetails: "Standard government rates",
    city: "Dhaka",
    area: "Khilgaon",
    address: "Taltola",
    amenities: ["Balcony", "Security", "Gas (Line)"],
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Md. Selim",
    ownerPhone: "01611223344",
    ownerId: "system_dummy_8"
  },
  {
    title: "Executive Bachelor Suite in Banani",
    category: "Bachelor",
    description: "Nicely decorated room with attached bath. Common kitchen and dining area.",
    rent: 15000,
    deposit: 15000,
    utilityDetails: "Flat rate 1500tk/mo for all",
    city: "Dhaka",
    area: "Banani",
    address: "Road 11",
    amenities: ["A/C", "Internet", "Lift", "Generator"],
    images: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Mrs. Nasreen",
    ownerPhone: "01999887766",
    ownerId: "system_dummy_9",
    isFeatured: true
  },
  {
    title: "Duplex Villa in Baridhara DOHS",
    category: "Family",
    description: "Exclusive duplex villa with 5 bedrooms and small garden.",
    rent: 120000,
    deposit: 300000,
    utilityDetails: "Individual bills",
    city: "Dhaka",
    area: "Baridhara DOHS",
    address: "Lane 5",
    amenities: ["Garden", "Parking", "Security", "Generator", "Balcony"],
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "General Mansur (Retd.)",
    ownerPhone: "01711224466",
    ownerId: "system_dummy_10"
  },
  {
    title: "Large Warehouse Space in Gazipur",
    category: "Office",
    description: "5000 sq ft high-ceiling warehouse/factory space with industrial power connection.",
    rent: 80000,
    deposit: 240000,
    utilityDetails: "Industrial sub-station",
    city: "Gazipur",
    area: "Tongi",
    address: "BSCIC Industrial Area",
    amenities: ["Security", "Parking", "Truck Loading Dock"],
    images: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Industrial Assets Ltd.",
    ownerPhone: "01300998877",
    ownerId: "system_dummy_11"
  },
  {
    title: "Sunny Bachelor Room in Mohammadpur",
    category: "Bachelor",
    description: "Large south facing room. Close to market and bus stand.",
    rent: 6500,
    deposit: 6500,
    utilityDetails: "Prepaid electricity",
    city: "Dhaka",
    area: "Mohammadpur",
    address: "Kaderabad Housing",
    amenities: ["Balcony", "Security"],
    images: ["https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Master Babu",
    ownerPhone: "01811667788",
    ownerId: "system_dummy_12"
  },
  {
    title: "New 3BHK Flat in Bashundhara",
    category: "Family",
    description: "Brand new building. Modern architecture and premium fittings.",
    rent: 42000,
    deposit: 84000,
    utilityDetails: "Gas line under process (cylinder allowed)",
    city: "Dhaka",
    area: "Bashundhara R/A",
    address: "Block L",
    amenities: ["Lift", "Generator", "Security", "Parking", "Balcony"],
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Mr. Faruk",
    ownerPhone: "01711001122",
    ownerId: "system_dummy_13"
  },
  {
    title: "Shared Office Desk in Core Banani",
    category: "Office",
    description: "Co-working desk space with all facilities. Ideal for freelancers.",
    rent: 7500,
    deposit: 7500,
    utilityDetails: "All inclusive",
    city: "Dhaka",
    area: "Banani",
    address: "Road 17",
    amenities: ["Internet", "Coffee Machine", "A/C", "Security"],
    images: ["https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&q=80&w=1000"],
    ownerName: "Hub Dhaka",
    ownerPhone: "01855667788",
    ownerId: "system_dummy_14"
  }
];

export const seedDatabase = async (ownerId: string) => {
  const propertiesCol = collection(db, 'properties');
  const promises = DUMMY_PROPERTIES.map(prop => 
    addDoc(propertiesCol, {
      ...prop,
      ownerId, // Use the provided ownerId (authenticated user)
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    })
  );
  await Promise.all(promises);
  return DUMMY_PROPERTIES.length;
};
